project_name: NengoBones
pkg_name: nengo_bones
repo_name: nengo/nengo-bones
license: abr-free
main_branch: main

description: Tools for managing Nengo projects
copyright_start: 2018

ci_scripts:
  - template: static
    pre_commands:
      - cat bones-scripts/static.sh
    post_commands:
      - "[ -f 'docs/tests/ignore-me.py' ]"
      - "[ ! -f 'docs/tests/test-example.py' ]"
  - template: test
    pre_commands:
      - cat bones-scripts/test.sh
      - export TEST_PRE_COMMANDS=True
    post_commands:
      - export TEST_POST_COMMANDS=True
  - template: test
    output_name: test-coverage
    coverage: true
    pre_commands:
      - cat bones-scripts/test-coverage.sh
      - export TEST_PRE_COMMANDS=True
      - . "$HOME/.nvm/nvm.sh"
      - nvm install 17
      - nvm use 17
      - npm install -g npm@latest-6
      - node --version
      # install prettier for use in bones-format-notebook
      - npm install prettier
    post_commands:
      - export TEST_POST_COMMANDS=True
  - template: test
    output_name: test-nengo
    nengo_tests: true
    pip_install:
      - nengo[tests]
    pre_commands:
      - cat bones-scripts/test-nengo.sh
      - export TEST_PRE_COMMANDS=True
    post_commands:
      - export TEST_POST_COMMANDS=True
  - template: remote
    pre_commands:
      - cat bones-scripts/remote.sh
    host: gl
  - template: test
    pre_commands:
      - cat bones-scripts/test-for-remote.sh
    output_name: test-for-remote
    coverage: true
  - template: remote-script
    pre_commands:
      - cat bones-scripts/remote-test.sh
    remote_script: test-for-remote
    output_name: remote-test
    host: gl
    coverage: true
  - template: docs
    pre_commands:
      - cat bones-scripts/docs.sh
    pip_install:
      - sphinx-click>=2.0.1
  - template: examples
    pre_commands:
      - cat bones-scripts/examples.sh
    pip_install:
      - mock
  - template: deploy
    wheel: true
    pre_commands:
      - cat bones-scripts/deploy.sh
  - template: auto-update
    pre_commands:
      - cat bones-scripts/auto-update.sh
    repos:
      - nengo/keras-lmu
      - nengo/keras-spiking
      - nengo/lmu
      - nengo/nengo
      - nengo/nengo-control
      - nengo/nengo-de1
      - nengo/nengo-de1-hw
      - nengo/nengo-dl
      - nengo/nengo-edge-device-plugins
      - nengo/nengo-edge-hw
      - nengo/nengo-edge-models
      - nengo/nengo-edge-server
      - nengo/nengo-fpga
      - nengo/nengo-interfaces
      - nengo/nengo-loihi
      - nengo/nengo-pynq
      - nengo/nengo-pynq-hw
      - nengo/nengo-spa
      - nengo/nengo-sphinx-theme
      - nengo/pytest-allclose
      - nengo/pytest-plt
      - nengo/pytest-rng
      - nengo/pytorch-spiking

contributing_rst: {}

contributors_rst: {}

license_rst: {}

manifest_in:
  recursive-include:
    - actions *.yml

setup_py:
  entry_points:
    console_scripts:
      - bones=nengo_bones.scripts.base:bones
  include_package_data: True
  # note: docs/tests_req are intentionally empty to test that the correct
  # requirements are built into the ci scripts
  install_req:
    - black>=21.12b0
    - click>=7.0
    - codespell>=2.0.0
    - docformatter>=1.5.0
    - flake8>=3.7.7
    - jinja2>=2.11
    - jupyter>=1.0.0
    - pylint>=2.5.1
    - pyyaml>=5.1
    - requests>=2.21
  tests_req:
    - check-manifest>=0.48
  classifiers:
    - "Development Status :: 4 - Beta"
    - "Framework :: Nengo"
    - "Intended Audience :: Developers"
    - "Operating System :: Microsoft :: Windows"
    - "Operating System :: POSIX :: Linux"
    - "Programming Language :: Python"
    - "Programming Language :: Python :: 3.6"
    - "Programming Language :: Python :: 3.7"
    - "Programming Language :: Python :: 3.8"
    - "Programming Language :: Python :: 3.9"
    - "Topic :: Software Development"

setup_cfg:
  pytest:
    addopts: []
    norecursedirs:
      - tests/ignoreme
    markers:
      test-marker: Not a real
        marker
    nengo_test_unsupported:
      "*": All tests are
        unsupported
  coverage:
    exclude_lines:
      - "if __name__ == .__main__.:"
    omit_files:
      - nengo_bones/tests/utils.py
      - nengo_bones/tests/ignoreme/*
  flake8:
    exclude:
      - nengo_bones/tests/ignoreme
  pylint:
    ignore:
      - ignoreme
  codespell:
    ignore_words:
      - coment
      - serach
    skip:
      - test_format_notebook.py

docs_conf_py:
  exclude_patterns:
    - tests/test-example.ipynb
  sphinx_options:
    suppress_warnings: '["image.nonlocal_uri"]'
  extensions:
    - sphinx_click.ext
  intersphinx_mapping:
    click: https://click.palletsprojects.com/en/7.x
  doctest_setup:
    - "# Testing that doctest_setup works"
    - "# with multiple lines"
  html_redirects:
    changelog.html: changes.html

pre_commit_config_yaml:
  exclude:
    - tests/ignoreme/ignoreme.py
    - tests/ignoreme/ignoreme.py

pyproject_toml:
  exclude:
    - tests/ignoreme/ignoreme.py
    - tests/ignoreme/ignoreme.py

version_py:
  type: calver
  release: true
