project_name: NengoBones
pkg_name: nengo_bones
repo_name: nengo/nengo-bones
main_branch: master

description: Tools for managing Nengo projects
copyright_start: 2018

travis_yml:
  python: 3.7
  global_vars:
    TEST_GLOBAL_VAR: test global var val
    TEST_LOCAL_VAR: this val will be overwritten
  jobs:
    - script: static
    - script: docs
    - script: examples
    - script: test
      cache: false
      env:
        TEST_LOCAL_VAR: test local var val
      test_args: --test-arg --test-arg
    - script: remote
    - script: remote-test
    - script: test-coverage
      env:
        TEST_LOCAL_VAR: test local var val
      test_args: --test-arg
    - script: test-coverage
      env:
        TEST_LOCAL_VAR: test local var val
      test_args: --test-arg
      python: 3.6
    - script: test-nengo
      env:
        TEST_LOCAL_VAR: test local var val
      test_args: --test-arg
      python: 3.9
      dist: bionic
    - stage: autoupdate
      script: auto-update
      if: type = push AND branch = master
  pypi_user: __token__
  deploy_dists:
    - sdist
    - bdist_wheel
  bones_install: git+https://github.com/nengo/nengo-bones.git@$BRANCH_NAME
  slack_notifications: "VVTPPxCrl53OAZeUojRa2SkG8JWdRbn/Lzfd1oVgMGZ1nKzBJsldWIvQX6pZHJ\
    88h6MJrEvc/xOzhCSqLQURnahElw5HqzUbTRCTJ7La6/X1Xow238bby1ZTIDgcVhl8tWX6dWrwiTUEDhSg\
    eSWcfQFLFnoY3uY8aiqvCXio/9+c8Ged3bA1bgfJRFwXcLvNWciYSK0KPMMHT8sXNrCPDzsJARXqmZN5dX\
    1XtLCgPNzC68ocsKv/kvp4jaj1BuNhdRMxdLIHDdQOhAx2VJGNSdY+/qjvEbomR+KYWAOusNIMYyEdoJdN\
    l4poCmaENs/YpxeP/qchNNPMsiDIi8WNphS3+A/VfdwzseOFWnkpH1+hAgEg0ZwNuYrW7+WL3TyJnV0uWD\
    xhnLUzdbNsZx0FxkjTYz29OgcybalwGYiBWzUAl2/V1iRV4U0zlcb2mAT/knGZuU9DIb7IkynOc0aoOfuL\
    Cul3a48Og3ehUujiTTFq11euYdBJghxsVCdivmBO9cfZN0hfIUO0fs63MvyM/a63KOUpDvVR4lOkq44/Xf\
    j2uvHUHRmoapkdy27pcSdbk5lnCqUOuAIvO6eA6u82XFUskEBZETB+2CfjRUDGRUVNx2vMgBlETW/Q3qDb\
    AywKqbMx1DLyAxzBcKHZOh9sfcdGfamW05q3ZrdjGrhj6uI="

codecov_yml: {}

ci_scripts:
  - template: static
    pre_commands:
      - cat .ci/static.sh
    post_commands:
      - "[ -f 'docs/tests/ignore-me.py' ]"
      - "[ ! -f 'docs/tests/test-example.py' ]"
  - template: test
    pre_commands:
      - cat .ci/test.sh
      - export TEST_PRE_COMMANDS=True
    post_commands:
      - export TEST_POST_COMMANDS=True
  - template: test
    output_name: test-coverage
    coverage: true
    pre_commands:
      - cat .ci/test-coverage.sh
      - export TEST_PRE_COMMANDS=True
      # update nodejs version
      - npm install -g npm@latest-6
      - npm install -g node --force
      - node --version
      # install prettier for use in bones-format-notebook
      - npm install prettier
    post_commands:
      - export TEST_POST_COMMANDS=True
  - template: test
    output_name: test-nengo
    nengo_tests: true
    pip_install:
      - nengo[tests]
    pre_commands:
      - cat .ci/test-nengo.sh
      - export TEST_PRE_COMMANDS=True
    post_commands:
      - export TEST_POST_COMMANDS=True
  - template: remote
    pre_commands:
      - cat .ci/remote.sh
    travis_var_key: 2895d60e3414
    host: gl
  - template: test
    pre_commands:
      - cat .ci/test-for-remote.sh
    output_name: test-for-remote
    coverage: true
  - template: remote-script
    pre_commands:
      - cat .ci/remote-test.sh
    remote_script: test-for-remote
    output_name: remote-test
    travis_var_key: 2895d60e3414
    host: gl
    coverage: true
  - template: docs
    pre_commands:
      - cat .ci/docs.sh
    pip_install:
      - sphinx-click>=2.0.1
  - template: examples
    pre_commands:
      - cat .ci/examples.sh
    pip_install:
      - mock
  - template: deploy
    pre_commands:
      - cat .ci/deploy.sh
  - template: auto-update
    pre_commands:
      - cat .ci/auto-update.sh
    repos:
      - nengo/keras-lmu
      - nengo/keras-spiking
      - nengo/lmu
      - nengo/nengo
      - nengo/nengo-control
      - nengo/nengo-de1
      - nengo/nengo-de1-hw
      - nengo/nengo-dl
      - nengo/nengo-fpga
      - nengo/nengo-interfaces
      - nengo/nengo-loihi
      - nengo/nengo-pynq
      - nengo/nengo-pynq-hw
      - nengo/nengo-spa
      - nengo/nengo-sphinx-theme
      - nengo/pytest-allclose
      - nengo/pytest-plt
      - nengo/pytest-rng
      - nengo/pytorch-spiking

contributing_rst: {}

contributors_rst: {}

license_rst: {}

manifest_in: {}

setup_py:
  entry_points:
    console_scripts:
      - bones-generate=nengo_bones.scripts.generate_bones:main
      - bones-check=nengo_bones.scripts.check_bones:main
      - bones-pr-number=nengo_bones.scripts.pr_number:main
      - bones-format-notebook=nengo_bones.scripts.format_notebook:main
  include_package_data: True
  # note: docs/tests_req are intentionally empty to test that the correct
  # requirements are built into the ci scripts
  install_req:
    - black>=21.12b0
    - click>=7.0
    - codespell>=2.0.0
    - flake8>=3.7.7
    - jinja2>=2.11
    - jupyter>=1.0.0
    - pylint>=2.5.1
    - astroid!=2.8.5  # see https://github.com/PyCQA/astroid/issues/1239
    - pyyaml>=5.1
    - requests>=2.21
  classifiers:
    - "Development Status :: 4 - Beta"
    - "Framework :: Nengo"
    - "Intended Audience :: Developers"
    - "License :: Free for non-commercial use"
    - "Operating System :: Microsoft :: Windows"
    - "Operating System :: POSIX :: Linux"
    - "Programming Language :: Python"
    - "Programming Language :: Python :: 3.6"
    - "Programming Language :: Python :: 3.7"
    - "Programming Language :: Python :: 3.8"
    - "Programming Language :: Python :: 3.9"
    - "Topic :: Software Development"

setup_cfg:
  pytest:
    addopts: []
    norecursedirs:
      - tests/ignoreme
    markers:
      test-marker:
        Not a real
        marker
    nengo_test_unsupported:
      "*":
        All tests are
        unsupported
  coverage:
    exclude_lines:
      - "if __name__ == .__main__.:"
    omit_files:
      - nengo_bones/tests/utils.py
      - nengo_bones/tests/ignoreme/*
  flake8:
    exclude:
      - nengo_bones/tests/ignoreme
  pylint:
    ignore:
      - ignoreme
  codespell:
    ignore_words:
      - coment
      - serach
    skip:
      - test_format_notebook.py

docs_conf_py:
  exclude_patterns:
    - tests/test-example.ipynb
  sphinx_options:
    suppress_warnings: '["image.nonlocal_uri"]'
  extensions:
    - sphinx_click.ext
  intersphinx_mapping:
    click: https://click.palletsprojects.com/en/7.x
  tagmanager_id: GTM-KWCR2HN
  doctest_setup:
    - "# Testing that doctest_setup works"
    - "# with multiple lines"
  html_redirects:
    changelog.html: changes.html

pre_commit_config_yaml:
  exclude:
    - tests/ignoreme/ignoreme.py
    - tests/ignoreme/ignoreme.py

pyproject_toml:
  exclude:
    - tests/ignoreme/ignoreme.py
    - tests/ignoreme/ignoreme.py

version_py:
  type: calver
  release: false
