pkg_name: nengo_bones
repo_name: nengo/nengo-bones

travis_yml:
  python_version: 3.6
  global_vars:
    TEST_GLOBAL_VAR: test global var val
    TEST_LOCAL_VAR: this val will be overwritten
  jobs:
    - script: static
    - script: docs
    - script: test
      cache: false
      env:
        TEST_LOCAL_VAR: test local var val
      test_args: --test-arg --test-arg
      python_version: 3.5
    - script: test-coverage
      env:
        TEST_LOCAL_VAR: test local var val
      test_args: --test-arg
    - script: examples
  pypi_user: drasmuss
  deploy_dists:
    - sdist
    - bdist_wheel

codecov_yml: {}

ci_scripts:
  - template: static
    pre_commands:
      - cat .ci/static.sh
  - template: test
    pre_commands:
      - cat .ci/test.sh
      - export TEST_PRE_COMMANDS=True
    post_commands:
      - export TEST_POST_COMMANDS=True
  - template: test
    pre_commands:
      - cat .ci/test-coverage.sh
      - export TEST_PRE_COMMANDS=True
    post_commands:
      - export TEST_POST_COMMANDS=True
    coverage: true
    output_name: test-coverage
  - template: docs
    pre_commands:
      - cat .ci/docs.sh
    pip_install:
      - mock
  - template: examples
    pre_commands:
      - cat .ci/examples.sh
    pip_install:
      - mock
  - template: deploy
    pre_commands:
      - cat .ci/deploy.sh
