name: Run script
description: Run a NengoBones script
inputs:
  name:
    description: Script name
    required: true
  path:
    description: Path to project directory (if not the current directory)
    required: false
    default: null
  scripts-dir:
    description: Path to folder containing generated scripts
    required: false
    default: bones-scripts
runs:
  using: composite
  steps:
    - name: Install
      shell: bash -el {0}
      working-directory: ${{ inputs.path }}
      run: |
        ${{ inputs.scripts-dir }}/${{ inputs.name }}.sh install
    - name: Display environment information
      shell: bash -el {0}
      run: |
        pip freeze
    - name: Install ssh debugging requirements
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}
      shell: bash -el {0}
      working-directory: ${{ inputs.path }}
      run: |
        sudo apt update -y
        sudo apt install -y openssh-client
    - name: Open debugging ssh session
      uses: lhotari/action-upterm@v1
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}
      env:
        # Undo any changes to the LD_LIBRARY_PATH so that the action will use the
        # versions installed with the openssh-client installation above
        LD_LIBRARY_PATH: ""
    - name: Script
      shell: bash -el {0}
      working-directory: ${{ inputs.path }}
      run: |
        ${{ inputs.scripts-dir }}/${{ inputs.name }}.sh script
    - name: After success
      if: ${{ success() }}
      shell: bash -el {0}
      working-directory: ${{ inputs.path }}
      run: |
        ${{ inputs.scripts-dir }}/${{ inputs.name }}.sh after_success
    - name: After failure
      if: ${{ failure() }}
      shell: bash -el {0}
      working-directory: ${{ inputs.path }}
      run: |
        ${{ inputs.scripts-dir }}/${{ inputs.name }}.sh after_failure
    - name: After script
      if: ${{ always() }}
      shell: bash -el {0}
      working-directory: ${{ inputs.path }}
      run: |
        ${{ inputs.scripts-dir }}/${{ inputs.name }}.sh after_script
