name: Setup python job
description: Common setup steps for a Python job
inputs:
  path:
    description: Relative path under github workspace in which to place the repository
    required: false
    default: null
  python-version:
    description: Python version (passed to actions/setup-python)
    required: false
    default: "3"
  cache:
    description: Enable/disable caching of pip/conda downloads
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ inputs.path }}
    - uses: mamba-org/setup-micromamba@v1
      with:
        create-args: python=${{ inputs.python-version }}
        environment-name: ci
        cache-downloads: ${{ inputs.cache }}
        generate-run-shell: false
    - uses: actions/cache@v4
      if: ${{ inputs.cache == 'true' }}
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
