name: Setup python job
description: Common setup steps for a Python job
inputs:
  path:
    description: Relative path under github workspace in which to place the repository
    required: false
    default: null
  python-version:
    description: Python version (passed to actions/setup-python)
    required: false
    default: "3"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ inputs.path }}
    - uses: mamba-org/setup-micromamba@v1
      with:
        create-args: python=${{ inputs.python-version }}
        environment-name: ci
        cache-downloads: true
        generate-run-shell: false
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
