# Automatically generated by nengo-bones, do not edit this file directly
# Version: 0.2.2.dev0

"""Nengo Bones version information.

We use semantic versioning (see http://semver.org/).
and conform to PEP440 (see https://www.python.org/dev/peps/pep-0440/).
'.dev0' will be added to the version unless the code base represents
a release version. Release versions are git tagged with the version.
The API of nengo-bones is different from other libraries, so we increment
version numbers as follows:

1. Major version when command line scripts change significantly.
2. Minor version when changes require patches to downstream projects.
3. Patch version when changes do not require downstream patches.

"""

name = "nengo-bones"
version_info = (0, 2, 2)
release = False
version = "0.2.2.dev0"
